### ISSUE TITLE
Update the `update_turn.py` script

### ISSUE THREAD

**Issue by kalekundert** [kxgames/seacow_spreadsheet_prototype#7]
- Add argument parsing for the "New Investments" column, e.g. tile ID for explore "investment".
- Update "Explored Tiles" column for each player.
- Reverse order of turn/income columns, so that most recent entries are first.
- Calculate the balance at the beginning of each turn for each player (because the spreadsheet is no longer smart enough to do this on its own).

**Comment by kalekundert** [comment]
Alex: hopefully you haven't started on this yet.  I'm about half-way through it now, but probably won't finish until Saturday/Sunday.

**Comment by alexmitchell** [comment]
Nope, all yours!
